[2025-01-25T06:38:36.448+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-25T06:38:36.486+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: model_prediction_dag.call_model_api_task scheduled__2025-01-24T00:00:00+00:00 [queued]>
[2025-01-25T06:38:36.515+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: model_prediction_dag.call_model_api_task scheduled__2025-01-24T00:00:00+00:00 [queued]>
[2025-01-25T06:38:36.516+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 4
[2025-01-25T06:38:36.593+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): call_model_api_task> on 2025-01-24 00:00:00+00:00
[2025-01-25T06:38:36.603+0000] {standard_task_runner.py:72} INFO - Started process 4753 to run task
[2025-01-25T06:38:36.608+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'model_prediction_dag', 'call_model_api_task', 'scheduled__2025-01-24T00:00:00+00:00', '--job-id', '133', '--raw', '--subdir', 'DAGS_FOLDER/travel_prediction.py', '--cfg-path', '/tmp/tmpx0uyi5gt']
[2025-01-25T06:38:36.613+0000] {standard_task_runner.py:105} INFO - Job 133: Subtask call_model_api_task
[2025-01-25T06:38:36.787+0000] {task_command.py:467} INFO - Running <TaskInstance: model_prediction_dag.call_model_api_task scheduled__2025-01-24T00:00:00+00:00 [running]> on host 7f618819d11e
[2025-01-25T06:38:37.029+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='model_prediction_dag' AIRFLOW_CTX_TASK_ID='call_model_api_task' AIRFLOW_CTX_EXECUTION_DATE='2025-01-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-24T00:00:00+00:00'
[2025-01-25T06:38:37.031+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-25T06:38:37.358+0000] {logging_mixin.py:190} INFO - Prediction: {'prediction': [630.4428]}
[2025-01-25T06:38:37.360+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-25T06:38:37.384+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-25T06:38:37.386+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=model_prediction_dag, task_id=call_model_api_task, run_id=scheduled__2025-01-24T00:00:00+00:00, execution_date=20250124T000000, start_date=20250125T063836, end_date=20250125T063837
[2025-01-25T06:38:37.510+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-25T06:38:37.542+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-25T06:38:37.544+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
