[2025-01-02T18:17:01.385+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-02T18:17:01.416+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: model_prediction_dag.call_model_api_task scheduled__2025-01-01T00:00:00+00:00 [queued]>
[2025-01-02T18:17:01.439+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: model_prediction_dag.call_model_api_task scheduled__2025-01-01T00:00:00+00:00 [queued]>
[2025-01-02T18:17:01.440+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 4
[2025-01-02T18:17:01.500+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): call_model_api_task> on 2025-01-01 00:00:00+00:00
[2025-01-02T18:17:01.511+0000] {standard_task_runner.py:72} INFO - Started process 2146 to run task
[2025-01-02T18:17:01.515+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'model_prediction_dag', 'call_model_api_task', 'scheduled__2025-01-01T00:00:00+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/travel_prediction.py', '--cfg-path', '/tmp/tmp9loxdx16']
[2025-01-02T18:17:01.517+0000] {standard_task_runner.py:105} INFO - Job 22: Subtask call_model_api_task
[2025-01-02T18:17:01.645+0000] {task_command.py:467} INFO - Running <TaskInstance: model_prediction_dag.call_model_api_task scheduled__2025-01-01T00:00:00+00:00 [running]> on host 23f622abfe56
[2025-01-02T18:17:01.791+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='model_prediction_dag' AIRFLOW_CTX_TASK_ID='call_model_api_task' AIRFLOW_CTX_EXECUTION_DATE='2025-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-01T00:00:00+00:00'
[2025-01-02T18:17:01.793+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-02T18:17:02.452+0000] {logging_mixin.py:190} INFO - Prediction: {'prediction': [630.4428]}
[2025-01-02T18:17:02.453+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-02T18:17:02.476+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-02T18:17:02.478+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=model_prediction_dag, task_id=call_model_api_task, run_id=scheduled__2025-01-01T00:00:00+00:00, execution_date=20250101T000000, start_date=20250102T181701, end_date=20250102T181702
[2025-01-02T18:17:02.580+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-02T18:17:02.615+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-02T18:17:02.620+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
